/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WBox: typeof import('@waltz-ui/ui')['WBox']
    WButton: typeof import('@waltz-ui/ui')['WButton']
    WForm: typeof import('@waltz-ui/ui')['WForm']
    WIcon: typeof import('@waltz-ui/ui')['WIcon']
    WPicture: typeof import('@waltz-ui/ui')['WPicture']
    WSwitch: typeof import('@waltz-ui/ui')['WSwitch']
  }
}
